.github/workflows/master.yml
.github/workflows/release.yml
Cargo.toml
Dockerfile

Building in the current image can lead to GLIBC linking errors in other systems, this builds the wheels in the appropriate `quay.io/pypa/manylinux1_x86_64` image.

Fix glibc linking

---

Cargo.toml

pyo3 0.10 added `catch_unwind!` macro to prevent panics crossing ffi boundaries https://github.com/PyO3/pyo3/pull/797 , which resolves #5, although ideally we should define some specific exceptions, but hey at least it's **not unsound** anymore.
```python
In [1]: import cramjam
In [2]: cramjam.snappy_decompress(b'abcdefgh')
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: StreamHeader { byte: 97 } }', src/snappy.rs:21:35
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
---------------------------------------------------------------------------
PanicException                            Traceback (most recent call last)
<ipython-input-2-1d4c0e441753> in <module>
----> 1 …
```

Upgrade pyo3 to 0.10.1

---

Cargo.toml
src/brotli.rs
src/deflate.rs
src/exceptions.rs
src/gzip.rs
src/lib.rs
src/lz4.rs
src/snappy.rs
src/zstd.rs
tests/test_variants.py

Will close #7 
Adds `cramjam.DecompressionError` and `cramjam.CompressionError` exceptions, removes all `unwrap()`s

Add appropriate python exceptions

---

.github/workflows/master.yml
.github/workflows/release.yml
Makefile
pypy_patch.py

Adds PyPy36 support.
- Needs to run `pypy_patch.py` after builds until https://github.com/PyO3/maturin/issues/312 is closed
- Cannot support Windows PyPy until https://github.com/PyO3/maturin/issues/115 is closed

Support PyPy builds

---

.github/workflows/CI.yml
Makefile

The culprit is that `extension-module` feature was disabled by accident.

Fix PyPy and linux cross compilation

---

.github/workflows/CI.yml
Cargo.toml
Makefile
README.md
src/brotli.rs
src/deflate.rs
src/exceptions.rs
src/gzip.rs
src/io.rs
src/lib.rs
src/lz4.rs
src/snappy.rs
src/zstd.rs
tests/test_rust_io.py
tests/test_variants.py

I think it would be cool to have file-like objects from the Rust side. This could allow side-stepping certain allocations to/from Python by allowing Rust to hold all the bytes. 
Most notably, compressing one file into another should be quite performant.
ie. 
```python
from cramjam import File, snappy
input_file = File("potentially-very-large-file.csv")
output_file = File("compressed-file.csv.snappy")
snappy.compress_into(input_file, output_file) 
```
and decompressing right into a buffer on the rust side:
```python
from cramjam import File, Buffer, snappy
input = File("some-file.csv.snappy")
decompressed = snappy.decompress(input)
decompressed.seek(0)
decompressed.read()  # decompressed bytes
```

Rust file-like objects and accept bytes/bytearray/numpy

---

.github/workflows/CI.yml
Cargo.toml
src/lib.rs
tests/test_no_numpy.py

Will fix #56 
Seems the `FromPyObject` evaluates in the order of the enum variants. Placing numpy as the last variant in `BytesType` will alleviate the error mentioned in #56.

Only fail on numpy import if using numpy

---

Cargo.toml

This makes it easier for automatic license checkers to verify the license of this package.

Add official OSI name in the license metadata

---

Cargo.lock
Cargo.toml
src/brotli.rs
src/deflate.rs
src/gzip.rs
src/io.rs
src/lz4.rs
src/snappy.rs
src/zstd.rs
tests/test_variants.py

#64 introduced streaming input, but of course, most will also want streaming output. :-)
Continues to follow the brotli API, such that flush will return what is currently compressed by the encoders and truncate its buff.
ie.
```python
>>> compressor = cramjam.snappy.Compressor()
>>> compressor.compress(b"foo")
>>> out = bytes(compressor.flush())
>>>
>>> compressor.compress(b"bar")
>>> out += bytes(compressor.flush())
>>>
>>> out += bytes(compressor.finish())
>>> decompressed = cramjam.snappy.decompress(out)
>>> assert bytes(decompressed) == b"foobar"
```
ref: https://github.com/developmentseed/starlette-cramjam/pull/1

Support .flush for Compressor

---

.github/workflows/CI.yml
Cargo.lock
Cargo.toml
src/io.rs

Dropped Python 3.6 support since pyo3 0.16 requires Python 3.7+.

Update to pyo3 0.16

---

Cargo.lock
Cargo.toml
src/lz4.rs
tests/test_variants.py

[lz4](https://github.com/10XGenomics/lz4-rs) adds de/compress_block_into functionality, mentioned in https://github.com/10XGenomics/lz4-rs/issues/16
This adds the following functions:
- [`cramjam.lz4.compress_block_into`](https://docs.rs/lz4/1.23.3/lz4/block/fn.compress_to_buffer.html)
- [`cramjam.lz4.decompress_block_into`](https://docs.rs/lz4/1.23.3/lz4/block/fn.decompress_to_buffer.html)
- [`cramjam.lz4.compress_block_bound`](https://docs.rs/lz4/1.23.3/lz4/block/fn.compress_bound.html)

Support Lz4 de/compress_block_into functions

---

.github/workflows/CI.yml

`actions-rs` appears to be unmaintained: https://github.com/actions-rs/toolchain/issues/216

Update github actions

---

Cargo.lock
cramjam-python/Cargo.toml
cramjam-python/src/io.rs
cramjam-python/src/lib.rs
cramjam-python/tests/test_variants.py

Support all buffer types where c-contiguous

---

cramjam-python/benchmarks/test_bench.py
cramjam-python/tests/test_rust_io.py

Supporting Python < 3.10 requires:
```python
isinstance(x, (A, B))
```
instead of:
```python
isinstance(x, A | B)
```

Simpler isinstance() calls

---

.github/workflows/CI.yml
Cargo.lock
cramjam-python/Cargo.toml
cramjam-python/src/io.rs

Support Python 3.12

---

cramjam-python/src/lz4.rs

Right now it's copy-pasted from `compress_block_into` method:
````
>>> print(cramjam.lz4.compress_block_bound.__doc__)
Determine the size of a buffer which is guaranteed to hold the result of block compression, will error if
data is too long to be compressed by lz4.
Python Example
--------------
```python
>>> cramjam.lz4.compress_block_into(
...     b'some bytes here',
...     output=output_buffer,
...     mode=Option[str],
...     acceleration=Option[int],
...     compression=Option[int],
...     store_size=Option[bool]
... )
```
````

Fix docstring for `lz4.compress_block_bound`

---

Cargo.lock
cramjam-python/Cargo.toml

This version has official support for Python 3.12:
https://github.com/PyO3/pyo3/releases/tag/v0.20.0

Use pyo3 0.20

---

cramjam-python/src/lz4.rs

This PR adds 2 parameters to `Compressor` class: `block_linked` to allow switching to independent block mode and `content_checksum` to allow disabling content checksum. The parameters are named the same way, as they are in [python-lz4](https://python-lz4.readthedocs.io/en/stable/lz4.frame.html#lz4.frame.compress).
Motivation. `cramjam` is used in `aiokafka` for most codecs, but it's not possible to use it for LZ4. The problem is that kafka broker doesn't support linked block mode (see [KIP-57](https://cwiki.apache.org/confluence/display/KAFKA/KIP-57+-+Interoperable+LZ4+Framing) for the reference). Although kafka broker does support content checksum, it doesn't use it itself and using it in producer may cause problems with some consumers.

Support independent mode in LZ4 compressor

---

Cargo.lock
libcramjam/Cargo.toml

Suggested in https://bugzilla.redhat.com/show_bug.cgi?id=2257076#c6.
See: https://github.com/gyscos/zstd-rs/tags

In libcramjam, bump zstd to 0.13.0 (to go with zstd-safe 7.0.0)

---

cramjam-cli/src/main.rs

By default, and as published on PyPI, the cramjam-cli binary is called `cramjam-cli` rather than `cramjam`.

Adjust the binary name in the cramjam-cli example

---

.github/workflows/CI.yml
Cargo.lock
cramjam-python/Cargo.toml
cramjam-python/build.rs
cramjam-python/src/io.rs
cramjam-python/src/lib.rs
cramjam-python/src/lz4.rs
cramjam-python/src/snappy.rs
cramjam-python/tests/conftest.py
cramjam-python/tests/test_rust_io.py
cramjam-python/tests/test_variants.py

Part of #142.
Raise on errors known to fail with PyPy.
- No `bytes` or `memoryview` for target output (only relavent for de/compress_into methods)
- Will sometimes fail with multidimensional numpy arrays depending on dtype, notably datetime dtypes and a few others.
Additionally this:
- Updates CI to run the tests on PyPy environments
- Update `PythonBuffer::as_slice_mut` to return a Result so we can raise if we're on PyPy in the context mentioned above for raising errors.
- Better checks from C api for checks comparing to `1` for true.
- Drops PyPy 3.7 and 3.8, adding 3.10 and keeping 3.9.
- Updates Cargo.lock
- Parametrized pypy builds for macos and linux, Windows fails but that's a bigger issue

PyPy raise on known errors

---

.github/workflows/CI.yml
Cargo.lock
cramjam-python/Cargo.toml

Will close #115 
Adds Windows PyPy 3.9 and 3.10 wheels to CI.

Add Windows PyPy

---

.github/workflows/CI.yml

Looking back at past runs, seems like the average time is between 22-28mins roughly. Which is not pleasant.

Migrate to ubicloud for linux builds

---

.github/workflows/CI.yml

Unfortunately I don't know how to add tests for this, I have manually checked the x64 musl build and that worked fine.

Add musl build in CI

---

cramjam-cli/Cargo.toml

Even though this PR doesn’t contain the necessary work to actually expose the new xz support in the CLI, there don’t appear to be any relevant backwards-incompatibilities from `libcramjam` 0.2.x to 0.3.x, so it should be safe to build with the current release. The executable still builds, and I used `pytest` to confirm the tests still pass, with this PR applied.
Applying this as a downstream patch for [`cramjam-cli` 0.1.1 in Fedora](https://src.fedoraproject.org/rpms/cramjam-cli) will allow me to avoid carrying a [`rust-libcramjam0.2` compat package](https://src.fedoraproject.org/rpms/rust-libcramjam0.2) in Fedora 40 and later. (I plan to use the compat package in the stable Fedora 38 and 39 releases to avoid breaking the C ABIs of the existing packaged `libcramjam` shared libraries.)

Update libcramjam crate to 0.3.0 in cramjam-cli

---

.github/workflows/CI-python.yml

Annoying upload-artifact@v4 is not additive, each upload overwrites the previous (, or just fails w/o setting `overwrite: true`). So falling back to v3, can possibly use the one I wrote [artifact-mover](https://github.com/marketplace/actions/artifact-mover) but that uses S3. Maybe stick with v3 until it's officially retired nov 2024 and something changes there before then.

Don't overwrite artifact on each job

---

Cargo.toml
src/igzip.rs

Further improvements in isal-rs implementation; should probably add the zlib and deflate impls here as well which are much faster than present implementation.
zlib would be a new addition as well, but is anyway available in flate2. 
After experimental phase, should we auto-enable it on 64bit platforms for gzip, zlib and deflate, falling back to flate2? Seems okay, but the default compression for gzip is 6, but for isal, only 0, 1, 3 are supported....maybe a change for a 3.0 release?

Bump libcramjam/isal-rs

---

Cargo.toml
README.md
src/experimental.rs
src/ideflate.rs
src/izlib.rs
src/lib.rs
src/zlib.rs
tests/test_variants.py

Adds ZLIB from flate2 backend
Adds ZLIB and DEFLATE from ISA-L backend on the `experimental` module.

Add zlib, izlib and ideflate

---

pyproject.toml

Through https://github.com/PyO3/maturin/pull/2391 via the recently released https://github.com/PyO3/maturin/releases/tag/v1.8.0, we've been seeing failing builds for `cramjam` in Pyodide ([logs](https://app.circleci.com/pipelines/github/pyodide/pyodide/8375/workflows/56df26fc-2fd3-4689-b20e-52a1a7a6347f/jobs/122629?invite=true#step-106-30059_80)).
I've opened this PR to fix the failure here, and I shall be applying this PR as a patch to fix the failing builds. If you'd like me to set it as a dynamic attribute or something else of your liking, please let me know. Thank you!
- List of changes for Maturin 1.8.0: https://github.com/PyO3/maturin/blob/main/Changelog.md#180

Updates for Maturin 1.8: add a version key in the project metadata #64

---

.github/workflows/CI.yml
Cargo.lock
Cargo.toml
README.md
benchmarks/test_bench.py
pyproject.toml
tests/test_blosc2.py

Kinda sad to do this, but most of the maintenance in this project is regarding the experimental modules like isal and blosc2. 
It's awfully fun trying to get these things working, but I just don't have the bandwidth lately. For now I'm going to remove blosc2 and igzip, izlib, and ideflate from the default builds. Still available in `experimental` feature or enabling those features as desired. Might come back later and add a `cramjam-experimental` package or something so `cramjam` "stable" doesn't cause so much noise to those maintaining platform packages.

Remove experimental codecs in default builds

---

Cargo.lock
Cargo.toml
pyproject.toml
src/io.rs
src/lz4.rs

Opening as a draft to see how CI feels about this change and because `lock().unwrap()` may swallow panics incorrectly.

Update PyO3 to 0.23

---

Cargo.toml

This is a follow-up to https://github.com/milesgranger/cramjam/pull/198.

Bump libcramjam -> 0.7 (in Cargo.toml, to match Cargo.lock)

---

Cargo.lock
Cargo.toml

https://github.com/PyO3/pyo3/blob/v0.24.1/CHANGELOG.md
It doesn’t appear that any source changes are needed. I tested this with:
```
$ uv venv
$ . .venv/bin/activate
(cramjam) $ uv pip install -e .[dev]
(cramjam) $ pytest -v -rs --ignore=benchmarks/
```

Update PyO3 to 0.24

---

src/lz4.rs
tests/test_integration.py

Will close #216 
Uses new `output_len` parameter to try to determine if size is prepended, falling back to trying the opposite in case we assumed wrong or the user got it wrong.
Additional help check if output_len is provided but the output length is smaller.

Fix lz4.decompress_block_into w/o prepended size

---

.github/workflows/CI.yml
Cargo.lock
Cargo.toml
Makefile
pyproject.toml
src/io.rs
tests/conftest.py
tests/test_buffer_view.py
tests/test_rust_io.py
tests/test_variants.py
uv.lock

See https://github.com/milesgranger/cramjam/issues/213#issuecomment-2888784450.
Makes tests that mutate buffers use a `bytearray`, which works on all builds.
Also fixes the build on PyPy - this was missed in a previous PyO3 update.

Ban mutating immutable buffers on the free-threaded build

---

.github/workflows/CI.yml
pyproject.toml

Workaround for https://github.com/milesgranger/cramjam/issues/201. I was hitting issues using `pytest-run-parallel` locally with the old hypothesis version. Passing `--assert='plain'` seems to avoid the crash.

unpin hypothesis and disable assertion rewrites in CI

---

pyproject.toml

Although source code contains stub files with type annotations, they are not included into the package. And the `__init__.py` is autogenerated by maturin, not used those provided in the source:
```shell
❯ unzip -l cramjam-2.11.0-cp314-cp314-macosx_11_0_arm64.whl
Archive:  cramjam-2.11.0-cp314-cp314-macosx_11_0_arm64.whl
Length      Date    Time    Name
---------  ---------- -----   ----
5561  07-27-2025 21:10   cramjam-2.11.0.dist-info/METADATA
104  07-27-2025 21:10   cramjam-2.11.0.dist-info/WHEEL
1070  07-27-2025 21:10   cramjam-2.11.0.dist-info/licenses/LICENSE
111  07-27-2025 21:10   cramjam/__init__.py
3722064  07-27-2025 21:10   cramjam/cramjam.cpython-314-darwin.so
480  07-27-2025 21:10   cramjam-2.11.0.dist-info/RECORD
---------                     -------
3729390 …
```

Configure `python-source` to include type stubs
