- .github/workflows/master.yml
- .github/workflows/release.yml
- Cargo.toml
https://github.com/PyO3/pyo3/releases/tag/v0.11.0
> Upgrade pyo3 to 0.11.0 and use stable Rust

- Dockerfile
> Change Dockerfile to use stable channel

- .github/workflows/release.yml
- Cargo.toml
- src/exceptions.rs
https://pyo3.rs/v0.13.1/building_and_distribution.html#py_limited_apiabi3
> Build abi3 wheels

- .github/workflows/master.yml
- Cargo.toml
- src/brotli.rs
- src/deflate.rs
- src/gzip.rs
- src/lib.rs
- src/lz4.rs
- src/snappy.rs
- src/zstd.rs
- tests/test_variants.py
> Fix slice based de/compression for all variants

- src/lib.rs
- tests/test_variants.py
> Add __version__ module attribute

- .github/workflows/CI.yml
1. Use [maturin-action](https://github.com/messense/maturin-action)
2. Add `manylinux_2_24_ppc64le` and `manylinux2014_s390x` wheel support
> Use maturin-action

- .github/workflows/CI.yml
- Makefile
- benchmark-requirements.txt
- benchmarks/test_bench.py
- dev-requirements.txt
> Run benchmarks as unit tests on CI

- .github/workflows/CI.yml
- Cargo.toml
- pyproject.toml
Also upgraded `zstd` to `0.9.0+zstd.1.5.0` along the way.
> Upgrade pyo3 to 0.14.1

- .github/workflows/CI.yml
Will close #75 
What do you think @messense? Maybe there is a more clever way to fix this?
> Don't skip 3.10 OSX Universal2 wheels

- Cargo.lock
- Cargo.toml
- pyproject.toml
Will close #89 
@messense can you confirm the additions to `pyproject.toml` here are sufficient to close #89 and feel free to suggest anything else that ought to be added. Thank you. :)
> Bump pyo3, numpy and expand pyproject.toml

- .github/workflows/CI.yml
> Add missing 3.11 Mac universal wheel

- Cargo.lock
- libcramjam/Cargo.toml
- libcramjam/src/zstd.rs
> Remove zstd-safe dep in libcramjam

- cramjam-cli/Cargo.toml
- cramjam-python/Cargo.toml
> Remove relative libcramjam dep for python builds

- Cargo.lock
- cramjam-python/src/io.rs
- cramjam-python/tests/test_variants.py
> Impl __eq__ for python Buffer

- .github/workflows/CI.yml
- Cargo.toml
- src/blosc2.rs
- src/brotli.rs
- src/bzip2.rs
- src/deflate.rs
- src/experimental.rs
- src/gzip.rs
- src/io.rs
- src/lib.rs
- src/lz4.rs
- src/snappy.rs
- src/xz.rs
- src/zstd.rs
Will close #165 
and followup to #167
> Update PyO3 0.20 -> 0.22 & Python 3.13

- .github/workflows/CI.yml
- Cargo.toml
> Add more feature configuration options

- Cargo.toml
- src/blosc2.rs
- src/experimental.rs
- src/lib.rs
Will close #171 
Flags to change link settings for xz, gzip/deflate
xref: https://github.com/cramjam/libcramjam/pull/8
> Expose linking flexibility for xz, gzip/deflate from libcramjam

- Cargo.toml
- src/lib.rs
> Exclude benchmarks from builds

- .github/workflows/CI.yml
- Cargo.lock
- Cargo.toml
- pyproject.toml
Part of https://github.com/milesgranger/cramjam/issues/204
> Update and add PyPy11

- Cargo.lock
- Cargo.toml
- pyproject.toml
- src/io.rs
- tests/conftest.py
- tests/test_buffer_view.py
- uv.lock
```python
In [1]: import cramjam
In [2]: data = b"bytes"
In [3]: buf = cramjam.Buffer(data, copy=False)
In [4]: buf.write(b'00')
Out[4]: 2
In [5]: data
Out[5]: b'00tes'
```
Also works with a changing underlying data buffer
```python
In [1]: import cramjam
In [2]: data = cramjam.Buffer()
In [3]: buf = cramjam.Buffer(data, copy=False)
In [4]: buf
Out[4]: cramjam.Buffer<len=0>
In [5]: data.write(b'bytes here')
Out[5]: 10
In [6]: buf
Out[6]: cramjam.Buffer<len=10>
In [7]: buf.write(b'foo bar')
Out[7]: 7
In [8]: data.seek(0)
Out[8]: 0
In [9]: data.read()
Out[9]: b'foo barere'
In [10]: data.set_len(2)
In [11]: buf
Out[11]: cramjam.Buffer<len=2>
In [12]: buf.tell()
Out[12]: 2
In [13]: buf.write(b'1')
---------------------------------------------------------------------------
OSError …
```
> Initial impl zero-copy Buffer

- .github/workflows/CI.yml
- tests/test_variants.py
Will close https://github.com/milesgranger/cramjam/issues/228
Also ensure hypothesis' derandomize is disabled - https://github.com/milesgranger/cramjam/issues/201#issuecomment-3132986379
> Add 3.8 for 2.11.0 release & disable hypothesis derandomize
